# Objetivo para compilar
build: main.scala
	scalac ./**/*.scala

# Objetivo para ejecutar
run: build
	scala main

# Objetivo para limpiar archivos compilados
clean:
	find . -name "*.class" -type f -delete
